### ISSUE TITLE
[question] customizing faces

### ISSUE THREAD

**Issue by ninrod** [Fanael/relative-line-numbers#10]
Hi @Fanael. 

You mention [here](https://github.com/Fanael/relative-line-numbers#faces) that there's a way to customize how the numbers are displayed. 

Apparently I have to tweak the *face* `relative-line-numbers`.

I want that the line numbers be always the same size no matter what theme I'm using. 

You can see in the screenshot below why that would be a problem. 

So how can I say to relative-line-numbers to use always a same size small number no matter what theme I'm using and what the font size is using the aforementioned face configuration?

Thanks in advance.

<img width="1273" alt="uniform-numbers" src="https://cloud.githubusercontent.com/assets/8352747/20247901/bce51632-a9bf-11e6-8759-5b0774c22e01.png">

**Comment by Fanael** [comment]
Set the `:height` attribute.
