### ISSUE TITLE
can't display properly after typing `G` in Evil normal mode when the file is longer than a screen's height

### ISSUE THREAD

**Issue by robturtle** [Fanael/relative-line-numbers#4]
GNU Emacs 24.3.1

When I opened a file, and use `G` command in evil-normal-mode to goto the last line of the file.
The line numbers will not display correctly.

The problem appears every time when scrolling down is necessary to finished the `G` command

**Comment by Fanael** [comment]
Works for me.

Can you provide a screenshot?

**Comment by robturtle** [comment]
It's not caused by itself. fixed by upgrading my .emacs.d config. 
sorry for disturbing u. : P
