### ISSUE TITLE
please explain differences with linum-relative

### ISSUE THREAD

**Issue by wbolster** [Fanael/relative-line-numbers#7]
Hi, it would be great if you could summarise (preferably in the readme) why this is a better solution than the `linum-relative` package at https://github.com/coldnew/linum-relative

Alternatively, please explain why the other one is better. ;-)

**Comment by Fanael** [comment]
It's already there:

> Please note that this package *does not* rely on `linum`.

**Comment by wbolster** [comment]
of course line numbering is only sometimes useful. that's why it has a toggle. ;)   e.g. vim-style navigation with evil is sometimes easier with relative numbers, e,g `13k` to go 13 lines up.
